# Generated by Django 5.0 on 2024-09-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=255)),
                ('vek', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_pojisteni', models.CharField(max_length=100)),
                ('datum_sjednani', models.DateField()),
                ('platnost_do', models.DateField()),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pojisteni', to='NovyProjekt.pojistenec')),
            ],
        ),
    ]
