# Generated by Django 5.1.2 on 2024-11-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovyProjekt.uzivatel'),
        ),
    ]
