# Generated by Django 5.0 on 2024-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojisteni',
            name='castka',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
