# Generated by Django 5.1.2 on 2024-11-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0002_alter_pojistenec_uzivatel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojistenec',
            old_name='uzivatel',
            new_name='user',
        ),
    ]
