# Generated by Django 5.0 on 2024-10-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0002_pojisteni_castka'),
    ]

    operations = [
        migrations.CreateModel(
            name='PojistnaUdalost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_udalosti', models.DateField()),
                ('popis', models.TextField()),
                ('status', models.CharField(choices=[('nahlášeno', 'Nahlášeno'), ('vyřešeno', 'Vyřešeno'), ('čeká na schválení', 'Čeká na schválení')], max_length=20)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pojisteni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pojistne_udalosti', to='NovyProjekt.pojisteni')),
            ],
        ),
    ]
