# Generated by Django 5.1.2 on 2025-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0003_rename_uzivatel_pojistenec_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatel',
            name='first_name',
            field=models.CharField(default='jmeno', max_length=50),
        ),
        migrations.AddField(
            model_name='uzivatel',
            name='last_name',
            field=models.CharField(default='přijmení', max_length=50),
        ),
    ]
