# Generated by Django 5.0 on 2024-10-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0003_pojistnaudalost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojisteni',
            name='predmet',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='typ_pojisteni',
            field=models.CharField(choices=[('majetek', 'Pojištění majetku (např. dům, byt)'), ('zivotni', 'Životní pojištění'), ('cestovni', 'Cestovní pojištění'), ('vozidla', 'Pojištění vozidel (povinné ručení, havarijní pojištění)'), ('zdravotni', 'Zdravotní pojištění'), ('urazove', 'Úrazové pojištění'), ('odpovednost', 'Pojištění odpovědnosti (škoda způsobená třetí osobě)'), ('domacnost', 'Pojištění domácnosti'), ('pravni_ochrana', 'Pojištění právní ochrany'), ('podnikani', 'Pojištění podnikatelských rizik')], max_length=100),
        ),
    ]
