# Generated by Django 5.0 on 2024-10-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0004_pojisteni_predmet_alter_pojisteni_typ_pojisteni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojisteni',
            old_name='predmet',
            new_name='predmet_pojisteni',
        ),
    ]
