# Generated by Django 5.1.2 on 2025-01-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0005_alter_uzivatel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
