# Generated by Django 5.1.2 on 2025-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0006_alter_pojistenec_user_alter_uzivatel_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
