# Generated by Django 5.1.2 on 2025-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0007_uzivatel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='vek',
            field=models.IntegerField(null=True),
        ),
    ]
