# Generated by Django 5.1.2 on 2025-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovyProjekt', '0008_alter_pojistenec_vek'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
